// AUTO-GENERATED by AI Design Kit — from semantic graph (single source of truth).
// Do not edit by hand to imitate components; change the semantic graph and recompile.
import React from "react";
import { Form } from "antd";
import { Switch } from "antd";
import { Button } from "antd";

/*
:root {
  --alert-error-background: #fff2f0;
  --alert-info-background: #e6f4ff;
  --alert-warning-background: #fffbe6;
  --badge-background: #1677ff;
  --button-danger-background: #ff4d4f;
  --button-default-background: #ffffff;
  --button-default-border: #d9d9d9;
  --button-height-md: 32;
  --button-primary-background: #1677ff;
  --button-primary-foreground: #ffffff;
  --button-radius: 6;
  --card-background: #ffffff;
  --card-title-fill: #000000d9;
  --color-bg-layout: #f5f5f5;
  --color-border-default: #d9d9d9;
  --color-brand-primary: #1677ff;
  --color-danger: #ff4d4f;
  --color-error-seed: #ff4d4f;
  --color-neutral-0: #ffffff;
  --color-neutral-1: #fafafa;
  --color-neutral-10: #000000;
  --color-neutral-2: #f5f5f5;
  --color-neutral-3: #f0f0f0;
  --color-neutral-5: #d9d9d9;
  --color-neutral-7: #8c8c8c;
  --color-neutral-9: #434343;
  --color-primary-seed: #1677ff;
  --color-success: #52c41a;
  --color-success-seed: #52c41a;
  --color-text-default: #000000d9;
  --color-text-disabled: #00000040;
  --color-text-secondary: #00000073;
  --color-warning: #faad14;
  --color-warning-seed: #faad14;
  --font-lineHeight-base: 1.5715;
  --font-size-base: 14;
  --input-background: #ffffff;
  --input-border-color: #d9d9d9;
  --input-height-md: 32;
  --menu-background: #ffffff;
  --menu-item-selected: #1677ff;
  --modal-background: #ffffff;
  --modal-mask-background: #00000073;
  --space-grid-unit: 8;
  --table-border-color: #d9d9d9;
  --table-header-background: #fafafa;
  --table-row-background: #ffffff;
  --table-row-bg-subtle: #fafafa;
  --tag-background: #fafafa;
  --theme-algorithm-default: defaultAlgorithm;
}

*/
export default function Untitled() {
  return (
    <div className="adk-page" data-system="ant-design">
      <Form onFinish="handleSubmit" layout="vertical">
        <Switch checked aria-label="邮件通知" />
        <Switch checked={false} aria-label="桌面推送" />
        <Switch checked aria-label="每周摘要" />
        <Button type="primary">保存设置</Button>
      </Form>
    </div>
  );
}
