"""语义图 → React/TSX。源是语义图，不是 .pen，避免丢语义。

用契约 code 段（import / component / propMap）生成真实组件 import 与 props。
token → CSS 变量（:root）。slot → children 组合；映射到 children 的 string prop → 文本子节点。
"""
from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

from ..contract import Contract, ContractIndex
from ..graph import GraphNode, SemanticGraph
from ..tokens import TokenGraph


def _escape_text(s: str) -> str:
    return str(s).replace("{", "{{").replace("}", "}}").replace('"', "'")


def _prop_map_for(c: Optional[Contract]) -> Dict[str, str]:
    if not c:
        return {}
    return c.code.get("propMap", {})


def _emit_node(node: GraphNode, idx: ContractIndex, indent: str) -> Tuple[str, List[str]]:
    """返回 (jsx 片段, 该节点收集的 import 语句列表)。"""
    c = idx.get(node.component)
    imports: List[str] = []
    comp_name = c.code.get("component", node.component.split(".")[-1].title()) if c else node.component.split(".")[-1].title()
    if c and c.code.get("import"):
        imports.append(c.code["import"])

    prop_map = _prop_map_for(c)
    # children prop：被映射到 children 的 string prop 作为文本子节点
    children_prop = None
    for contract_prop, code_prop in prop_map.items():
        if code_prop == "children":
            children_prop = contract_prop
            break

    attrs: List[str] = []
    inline_children: List[str] = []
    for k, v in node.props.items():
        if children_prop and k == children_prop:
            inline_children.append(_escape_text(v))
            continue
        mapped = prop_map.get(k, k)
        if isinstance(v, bool):
            if v:
                attrs.append(mapped)
            else:
                attrs.append(f"{mapped}={{false}}")
        elif isinstance(v, (int, float)):
            attrs.append(f"{mapped}={{{v}}}")
        elif v is None:
            continue
        else:
            attrs.append(f'{mapped}="{_escape_text(v)}"')
    # variant 映射成 props（如 variant.intent -> type）
    if c:
        for axis, val in node.variant.items():
            # 约定：变体轴若在 propMap 中（如 intent->type）则映射，否则按 axis 名传
            mapped = prop_map.get(axis)
            key = mapped or axis
            if mapped or True:
                # 避免重复（若 variant 轴与已有 prop 同名）
                attr_line = f'{key}="{_escape_text(val)}"'
                if key not in [a.split("=")[0] for a in attrs]:
                    attrs.append(attr_line)

    # slot/children 子节点
    slot_kids: List[str] = []
    for sname, kids in node.slots.items():
        for k in kids:
            jsx, imp = _emit_node(k, idx, indent + "  ")
            slot_kids.append(jsx)
            imports.extend(imp)
    for k in node.children:
        jsx, imp = _emit_node(k, idx, indent + "  ")
        slot_kids.append(jsx)
        imports.extend(imp)

    all_children = inline_children + slot_kids
    attr_str = (" " + " ".join(attrs)) if attrs else ""
    open_tag = f"<{comp_name}{attr_str}"
    if not all_children:
        return f"{indent}{open_tag} />", imports
    if len(all_children) == 1 and inline_children and not slot_kids:
        return f"{indent}{open_tag}>{all_children[0]}</{comp_name}>", imports
    body = "\n".join(all_children)
    return f"{indent}{open_tag}>\n{body}\n{indent}</{comp_name}>", imports


def _css_vars(tg: Optional[TokenGraph], mode: Optional[str]) -> str:
    if not tg:
        return ""
    use_mode = mode or tg.default_mode
    lines = [f"  --{k.replace('.', '-')}: {tg.resolve(k, use_mode)};" for k in sorted(tg.tokens)]
    return ":root {\n" + "\n".join(lines) + "\n}\n" if lines else ""


def compile_react(graph: SemanticGraph, idx: ContractIndex, tg: Optional[TokenGraph] = None) -> str:
    mode = graph.project.get("themeMode")
    imports: List[str] = []
    roots: List[str] = []
    for page in graph.pages:
        for root in graph.roots_by_page.get(page["id"], []):
            jsx, imp = _emit_node(root, idx, "      ")
            roots.append(jsx)
            imports.extend(imp)
    # 去重 import
    seen: Set[str] = set()
    unique_imports = [i for i in imports if not (i in seen or seen.add(i))]
    comp_name = "".join(p.title() for p in graph.project.get("name", "Page").replace("-", " ").split()) or "Page"
    body = "\n".join(roots)
    css = _css_vars(tg, mode)
    return f"""// AUTO-GENERATED by AI Design Kit — from semantic graph (single source of truth).
// Do not edit by hand to imitate components; change the semantic graph and recompile.
import React from "react";
{chr(10).join(unique_imports)}

/*
{css}
*/
export default function {comp_name}() {{
  return (
    <div className="adk-page" data-system="{graph.project.get('system', '')}">
{body}
    </div>
  );
}}
"""
