// AUTO-GENERATED by AI Design Kit — from semantic graph (single source of truth).
// Do not edit by hand to imitate components; change the semantic graph and recompile.
import React from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardAction, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

/*
:root {
  --background: 0 0% 100%;
  --border: 240 5.9% 90%;
  --destructive: 0 72.2% 50.6%;
  --foreground: 240 10% 3.9%;
  --muted: 240 4.8% 95.9%;
  --muted-foreground: 240 3.8% 46.1%;
  --primary: 240 5.9% 10%;
  --primary-foreground: 0 0% 98%;
  --radius: 0.5;
  --ring: 240 5.9% 10%;
}

*/
export default function Untitled() {
  return (
    <div className="adk-page" data-system="shadcn">
      <Card>
        <Button variant="link">Login to your account</Button>
        <Input type="email" placeholder="m@example.com" id="email" required />
        <Button type="submit" variant="default">Login</Button>
      </Card>
    </div>
  );
}
