// AUTO-GENERATED by AI Design Kit — from semantic graph (single source of truth).
// Do not edit by hand to imitate components; change the semantic graph and recompile.
import React from "react";
import { Layout } from "antd";
import { Menu } from "antd";
import { Breadcrumb } from "antd";
import { Input } from "antd";
import { Select } from "antd";
import { Button } from "antd";
import { Table } from "antd";
import { Modal } from "antd";
import { Typography } from "antd";

/*
:root {
  --alert-error-background: #fff2f0;
  --alert-info-background: #e6f4ff;
  --alert-warning-background: #fffbe6;
  --badge-background: #1677ff;
  --button-danger-background: #ff4d4f;
  --button-default-background: #ffffff;
  --button-default-border: #d9d9d9;
  --button-height-md: 32;
  --button-primary-background: #1677ff;
  --button-primary-foreground: #ffffff;
  --button-radius: 6;
  --card-background: #ffffff;
  --card-title-fill: #000000d9;
  --color-bg-layout: #f5f5f5;
  --color-border-default: #d9d9d9;
  --color-brand-primary: #1677ff;
  --color-danger: #ff4d4f;
  --color-error-seed: #ff4d4f;
  --color-neutral-0: #ffffff;
  --color-neutral-1: #fafafa;
  --color-neutral-10: #000000;
  --color-neutral-2: #f5f5f5;
  --color-neutral-3: #f0f0f0;
  --color-neutral-5: #d9d9d9;
  --color-neutral-7: #8c8c8c;
  --color-neutral-9: #434343;
  --color-primary-seed: #1677ff;
  --color-success: #52c41a;
  --color-success-seed: #52c41a;
  --color-text-default: #000000d9;
  --color-text-disabled: #00000040;
  --color-text-secondary: #00000073;
  --color-warning: #faad14;
  --color-warning-seed: #faad14;
  --font-lineHeight-base: 1.5715;
  --font-size-base: 14;
  --input-background: #ffffff;
  --input-border-color: #d9d9d9;
  --input-height-md: 32;
  --menu-background: #ffffff;
  --menu-item-selected: #1677ff;
  --modal-background: #ffffff;
  --modal-mask-background: #00000073;
  --space-grid-unit: 8;
  --table-border-color: #d9d9d9;
  --table-header-background: #fafafa;
  --table-row-background: #ffffff;
  --table-row-bg-subtle: #fafafa;
  --tag-background: #fafafa;
  --theme-algorithm-default: defaultAlgorithm;
}

*/
export default function Untitled() {
  return (
    <div className="adk-page" data-system="ant-design">
      <Layout structure="hasSider">
        <Menu items="[{{'key': 'users', 'label': '用户管理'}}, {{'key': 'roles', 'label': '角色管理'}}, {{'key': 'audit', 'label': '审计日志'}}]" selectedKeys="['users']" mode="inline" />
        <Breadcrumb items="[{{'title': '系统'}}, {{'title': '权限'}}, {{'title': '用户管理'}}]" />
        <Input label="搜索用户" value="" placeholder="按姓名/邮箱搜索" intent="search" />
        <Select options="[{{'label': '全部角色', 'value': 'all'}}, {{'label': '管理员', 'value': 'admin'}}, {{'label': '编辑', 'value': 'editor'}}]" placeholder="按角色筛选" mode="single" />
        <Button type="primary" size="middle">新增用户</Button>
        <Table rowKey="key" loading={false} columns="[{{'title': '姓名', 'dataIndex': 'name', 'key': 'name'}}, {{'title': '角色', 'dataIndex': 'role', 'key': 'role'}}, {{'title': '状态', 'dataIndex': 'status', 'key': 'status'}}, {{'title': '操作', 'key': 'action'}}]" dataSource="[{{'key': '1', 'name': '张三', 'role': 'admin', 'status': 'active'}}, {{'key': '2', 'name': '李四', 'role': 'editor', 'status': 'active'}}]" density="default" zebra="striped" />
      </Layout>
      <Modal open={false} title="确认删除该用户？" okText="确认删除" cancelText="取消" intent="confirm">
        <Button type="default">取消</Button>
        <Button type="danger">确认删除</Button>
        <Typography children="此操作不可撤销，确定要删除该用户吗？" variant="body" />
      </Modal>
    </div>
  );
}
